[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix frontend"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.zahara.ai wss://api.zahara.ai"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (optional - if you want to proxy API calls)
[[redirects]]
  from = "/api/*"
  to = "https://api.zahara.ai/:splat"
  status = 200
  force = true

# Development context
[context.branch-deploy]
  command = "cd frontend && npm ci && npm run build"
  
[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://dev-api.zahara.ai"
  VITE_DEV_MODE = "true"

# Deploy preview context
[context.deploy-preview]
  command = "cd frontend && npm ci && npm run build"
  
[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://staging-api.zahara.ai"
  VITE_DEV_MODE = "true"

# Production context
[context.production]
  command = "cd frontend && npm ci && npm run build"
  
[context.production.environment]
  VITE_API_BASE_URL = "https://api.zahara.ai"
  VITE_DEV_MODE = "false"
